export const trainData = [
  { text: 'coleira quebrada', urgency: 'high', area: 'collar' },
  { text: 'antena caiu', urgency: 'high', area: 'antenna' },
  { text: 'internet cai constantemente', urgency: 'medium', area: 'internet' },
  { text: 'fonte oscilando', urgency: 'medium', area: 'power' },
  { text: 'coleira rachada no canto', urgency: 'high', area: 'collar' },
  { text: 'coleira não transmite sinal', urgency: 'high', area: 'collar' },
  { text: 'antena sem sinal', urgency: 'high', area: 'antenna' },
  { text: 'antena offline', urgency: 'high', area: 'antenna' },
  { text: 'internet lenta', urgency: 'medium', area: 'internet' },
  { text: 'internet com perda de pacotes', urgency: 'medium', area: 'internet' },
  { text: 'fonte queimada', urgency: 'high', area: 'power' },
  { text: 'fonte não liga', urgency: 'high', area: 'power' },
  { text: 'coleira com bateria descarregada', urgency: 'medium', area: 'collar' },
  { text: 'antena com sinal fraco', urgency: 'medium', area: 'antenna' },
  { text: 'coleira com LED apagado', urgency: 'medium', area: 'collar' },
  { text: 'coleira com superaquecimento', urgency: 'high', area: 'collar' },
  { text: 'coleira com cheiro de queimado', urgency: 'high', area: 'collar' },
  { text: 'coleira com vazamento interno', urgency: 'high', area: 'collar' },
  { text: 'antena com conexão instável', urgency: 'medium', area: 'antenna' },
  { text: 'antena com LED apagado', urgency: 'medium', area: 'antenna' },
  { text: 'antena com superaquecimento', urgency: 'high', area: 'antenna' },
  { text: 'antena com cheiro de queimado', urgency: 'high', area: 'antenna' },
  { text: 'antena com vazamento interno', urgency: 'high', area: 'antenna' },
  { text: 'internet com conexão instável', urgency: 'medium', area: 'internet' },
  { text: 'internet com LED apagado', urgency: 'low', area: 'internet' },
  { text: 'internet com superaquecimento', urgency: 'low', area: 'internet' },
  { text: 'internet com cheiro de plástico queimado', urgency: 'low', area: 'internet' },
  { text: 'internet com vazamento de dados', urgency: 'low', area: 'internet' },
  { text: 'fonte com LED apagado', urgency: 'medium', area: 'power' },
  { text: 'fonte com superaquecimento', urgency: 'high', area: 'power' },
  { text: 'fonte com cheiro de queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com vazamento interno', urgency: 'high', area: 'power' },
  { text: 'coleira com componente estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com placa queimada', urgency: 'high', area: 'collar' },
  { text: 'coleira com solda fria', urgency: 'high', area: 'collar' },
  { text: 'coleira com trilha quebrada', urgency: 'high', area: 'collar' },
  { text: 'antena com componente estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com placa queimada', urgency: 'high', area: 'antenna' },
  { text: 'antena com solda fria', urgency: 'high', area: 'antenna' },
  { text: 'antena com trilha quebrada', urgency: 'high', area: 'antenna' },
  { text: 'internet com componente estourado', urgency: 'high', area: 'internet' },
  { text: 'internet com placa queimada', urgency: 'high', area: 'internet' },
  { text: 'internet com solda fria', urgency: 'high', area: 'internet' },
  { text: 'internet com trilha quebrada', urgency: 'high', area: 'internet' },
  { text: 'fonte com componente estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com placa queimada', urgency: 'high', area: 'power' },
  { text: 'fonte com solda fria', urgency: 'high', area: 'power' },
  { text: 'fonte com trilha quebrada', urgency: 'high', area: 'power' },
  { text: 'coleira com conector solto', urgency: 'medium', area: 'collar' },
  { text: 'coleira com fiação exposta', urgency: 'high', area: 'collar' },
  { text: 'coleira com vibração excessiva', urgency: 'medium', area: 'collar' },
  { text: 'coleira com bateria inchada', urgency: 'high', area: 'collar' },
  { text: 'antena com conector solto', urgency: 'medium', area: 'antenna' },
  { text: 'antena com fiação exposta', urgency: 'high', area: 'antenna' },
  { text: 'antena com vibração excessiva', urgency: 'medium', area: 'antenna' },
  { text: 'antena com bateria inchada', urgency: 'high', area: 'antenna' },
  { text: 'internet com conector solto', urgency: 'medium', area: 'internet' },
  { text: 'internet com fiação exposta', urgency: 'high', area: 'internet' },
  { text: 'internet com vibração excessiva', urgency: 'medium', area: 'internet' },
  { text: 'internet com bateria inchada', urgency: 'high', area: 'internet' },
  { text: 'fonte com conector solto', urgency: 'medium', area: 'power' },
  { text: 'fonte com fiação exposta', urgency: 'high', area: 'power' },
  { text: 'fonte com vibração excessiva', urgency: 'medium', area: 'power' },
  { text: 'fonte com bateria inchada', urgency: 'high', area: 'power' },
  { text: 'coleira com carcaça trincada', urgency: 'high', area: 'collar' },
  { text: 'coleira com ícone quebrado', urgency: 'high', area: 'collar' },
  { text: 'coleira com tela quebrada', urgency: 'high', area: 'collar' },
  { text: 'coleira com touch falhando', urgency: 'high', area: 'collar' },
  { text: 'antena com carcaça trincada', urgency: 'high', area: 'antenna' },
  { text: 'antena com ícone quebrado', urgency: 'high', area: 'antenna' },
  { text: 'antena com tela quebrada', urgency: 'high', area: 'antenna' },
  { text: 'antena com touch falhando', urgency: 'high', area: 'antenna' },
  { text: 'internet com carcaça trincada', urgency: 'high', area: 'internet' },
  { text: 'internet com ícone quebrado', urgency: 'low', area: 'internet' },
  { text: 'internet com tela quebrada', urgency: 'low', area: 'internet' },
  { text: 'internet com touch falhando', urgency: 'low', area: 'internet' },
  { text: 'fonte com carcaça trincada', urgency: 'high', area: 'power' },
  { text: 'fonte com ícone quebrado', urgency: 'high', area: 'power' },
  { text: 'fonte com tela quebrada', urgency: 'high', area: 'power' },
  { text: 'fonte com touch falhando', urgency: 'high', area: 'power' },
  { text: 'coleira com sensor de temperatura errado', urgency: 'medium', area: 'collar' },
  { text: 'coleira com GPS deslocado', urgency: 'medium', area: 'collar' },
  { text: 'coleira com bateria não carregando', urgency: 'high', area: 'collar' },
  { text: 'coleira com LED piscando', urgency: 'medium', area: 'collar' },
  { text: 'coleira com botão duplo clique falhando', urgency: 'medium', area: 'collar' },
  { text: 'antena com sensor de temperatura errado', urgency: 'medium', area: 'antenna' },
  { text: 'antena com GPS deslocado', urgency: 'medium', area: 'antenna' },
  { text: 'antena com bateria não carregando', urgency: 'high', area: 'antenna' },
  { text: 'antena com LED piscando', urgency: 'medium', area: 'antenna' },
  { text: 'antena com botão duplo clique falhando', urgency: 'medium', area: 'antenna' },
  { text: 'internet com sensor de temperatura errado', urgency: 'low', area: 'internet' },
  { text: 'internet com GPS deslocado', urgency: 'low', area: 'internet' },
  { text: 'internet com bateria não carregando', urgency: 'low', area: 'internet' },
  { text: 'internet com LED piscando', urgency: 'low', area: 'internet' },
  { text: 'internet com botão duplo clique falhando', urgency: 'low', area: 'internet' },
  { text: 'fonte com sensor de temperatura errado', urgency: 'medium', area: 'power' },
  { text: 'fonte com GPS deslocado', urgency: 'medium', area: 'power' },
  { text: 'fonte com bateria não carregando', urgency: 'high', area: 'power' },
  { text: 'fonte com LED piscando', urgency: 'medium', area: 'power' },
  { text: 'fonte com botão duplo clique falhando', urgency: 'medium', area: 'power' },
  { text: 'coleira com vibrador não funcionando', urgency: 'medium', area: 'collar' },
  { text: 'coleira com som distorcido', urgency: 'low', area: 'collar' },
  { text: 'coleira com carregador não reconhecido', urgency: 'medium', area: 'collar' },
  { text: 'coleira com porta USB solta', urgency: 'medium', area: 'collar' },
  { text: 'coleira com tampa traseira quebrada', urgency: 'high', area: 'collar' },
  { text: 'antena com vibrador não funcionando', urgency: 'medium', area: 'antenna' },
  { text: 'antena com som distorcido', urgency: 'low', area: 'antenna' },
  { text: 'antena com carregador não reconhecido', urgency: 'medium', area: 'antenna' },
  { text: 'antena com porta USB solta', urgency: 'medium', area: 'antenna' },
  { text: 'antena com tampa traseira quebrada', urgency: 'high', area: 'antenna' },
  { text: 'internet com vibrador não funcionando', urgency: 'low', area: 'internet' },
  { text: 'internet com som distorcido', urgency: 'low', area: 'internet' },
  { text: 'internet com carregador não reconhecido', urgency: 'low', area: 'internet' },
  { text: 'internet com porta USB solta', urgency: 'low', area: 'internet' },
  { text: 'internet com tampa traseira quebrada', urgency: 'low', area: 'internet' },
  { text: 'fonte com vibrador não funcionando', urgency: 'medium', area: 'power' },
  { text: 'fonte com som distorcido', urgency: 'low', area: 'power' },
  { text: 'fonte com carregador não reconhecido', urgency: 'medium', area: 'power' },
  { text: 'fonte com porta USB solta', urgency: 'medium', area: 'power' },
  { text: 'fonte com tampa traseira quebrada', urgency: 'high', area: 'power' },
  { text: 'coleira com ícone desalinhado', urgency: 'low', area: 'collar' },
  { text: 'coleira com bateria com vida útil baixa', urgency: 'medium', area: 'collar' },
  { text: 'coleira com sensor de batida falhando', urgency: 'high', area: 'collar' },
  { text: 'coleira com chip deslocado', urgency: 'medium', area: 'collar' },
  { text: 'antena com ícone desalinhado', urgency: 'low', area: 'antenna' },
  { text: 'antena com bateria com vida útil baixa', urgency: 'medium', area: 'antenna' },
  { text: 'antena com sensor de batida falhando', urgency: 'high', area: 'antenna' },
  { text: 'antena com chip deslocado', urgency: 'medium', area: 'antenna' },
  { text: 'internet com ícone desalinhado', urgency: 'low', area: 'internet' },
  { text: 'internet com bateria com vida útil baixa', urgency: 'low', area: 'internet' },
  { text: 'internet com sensor de batida falhando', urgency: 'high', area: 'internet' },
  { text: 'internet com chip deslocado', urgency: 'low', area: 'internet' },
  { text: 'fonte com ícone desalinhado', urgency: 'low', area: 'power' },
  { text: 'fonte com bateria com vida útil baixa', urgency: 'medium', area: 'power' },
  { text: 'fonte com sensor de batida falhando', urgency: 'high', area: 'power' },
  { text: 'fonte com chip deslocado', urgency: 'medium', area: 'power' },
  { text: 'fonte com placa com umidade', urgency: 'high', area: 'power' },
  { text: 'fonte com componente oxidado', urgency: 'high', area: 'power' },
  { text: 'fonte com trilha de fumaça', urgency: 'high', area: 'power' },
  { text: 'fonte com cheiro de plástico queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com superaquecimento na bateria', urgency: 'high', area: 'power' },
  // ===== MAIS 136 FRASES MISTURADAS (SORTIDAS) =====
  { text: 'coleira com antena interna danificada', urgency: 'high', area: 'collar' },
  { text: 'coleira com chip não detectado', urgency: 'high', area: 'collar' },
  { text: 'coleira com placa com umidade', urgency: 'high', area: 'collar' },
  { text: 'coleira com componente oxidado', urgency: 'high', area: 'collar' },
  { text: 'coleira com trilha de fumaça', urgency: 'high', area: 'collar' },
  { text: 'coleira com cheiro de plástico queimado', urgency: 'high', area: 'collar' },
  { text: 'coleira com superaquecimento na bateria', urgency: 'high', area: 'collar' },
  { text: 'coleira com vazamento de eletrólito', urgency: 'high', area: 'collar' },
  { text: 'coleira com bulbo estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com solda derretida', urgency: 'high', area: 'collar' },
  { text: 'coleira com componente estourado visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com trilha de fogo', urgency: 'high', area: 'collar' },
  { text: 'coleira com cheiro de metal queimado', urgency: 'high', area: 'collar' },
  { text: 'coleira com superaquecimento no transformador', urgency: 'high', area: 'collar' },
  { text: 'coleira com vazamento de óleo', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com resistor queimado', urgency: 'high', area: 'collar' },
  { text: 'coleira com indutor estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com diodo queimado', urgency: 'high', area: 'collar' },
  { text: 'coleira com transistor estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com integrado estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com CI estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com chip estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com microcontrolador estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com microprocessador estourado', urgency: 'high', area: 'collar' },
  { text: 'coleira com memória estourada', urgency: 'high', area: 'collar' },
  { text: 'coleira com RAM estourada', urgency: 'high', area: 'collar' },
  { text: 'coleira com ROM estourada', urgency: 'high', area: 'collar' },
  { text: 'coleira com Flash estourada', urgency: 'high', area: 'collar' },
  { text: 'coleira com EEPROM estourada', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor inflado', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor estourado visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com inchamento', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com fuga', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com trinca', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com rachadura', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com fissura', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com quebra', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com fratura', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com defeito', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com falha', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com problema', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com erro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vício', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material visível', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material notório', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material óbvio', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material claro', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de substância evidente', urgency: 'high', area: 'collar' },
  { text: 'coleira com capacitor com vazamento de material evidente', urgency: 'high', area: 'collar' },

  // ===== ANTENNA (50) =====
  { text: 'antena com antena interna danificada', urgency: 'high', area: 'antenna' },
  { text: 'antena com chip não detectado', urgency: 'high', area: 'antenna' },
  { text: 'antena com placa com umidade', urgency: 'high', area: 'antenna' },
  { text: 'antena com componente oxidado', urgency: 'high', area: 'antenna' },
  { text: 'antena com trilha de fumaça', urgency: 'high', area: 'antenna' },
  { text: 'antena com cheiro de plástico queimado', urgency: 'high', area: 'antenna' },
  { text: 'antena com superaquecimento na bateria', urgency: 'high', area: 'antenna' },
  { text: 'antena com vazamento de eletrólito', urgency: 'high', area: 'antenna' },
  { text: 'antena com bulbo estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com solda derretida', urgency: 'high', area: 'antenna' },
  { text: 'antena com componente estourado visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com trilha de fogo', urgency: 'high', area: 'antenna' },
  { text: 'antena com cheiro de metal queimado', urgency: 'high', area: 'antenna' },
  { text: 'antena com superaquecimento no transformador', urgency: 'high', area: 'antenna' },
  { text: 'antena com vazamento de óleo', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com resistor queimado', urgency: 'high', area: 'antenna' },
  { text: 'antena com indutor estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com diodo queimado', urgency: 'high', area: 'antenna' },
  { text: 'antena com transistor estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com integrado estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com CI estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com chip estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com microcontrolador estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com microprocessador estourado', urgency: 'high', area: 'antenna' },
  { text: 'antena com memória estourada', urgency: 'high', area: 'antenna' },
  { text: 'antena com RAM estourada', urgency: 'high', area: 'antenna' },
  { text: 'antena com ROM estourada', urgency: 'high', area: 'antenna' },
  { text: 'antena com Flash estourada', urgency: 'high', area: 'antenna' },
  { text: 'antena com EEPROM estourada', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor inflado', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor estourado visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com inchamento', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com fuga', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com trinca', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com rachadura', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com fissura', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com quebra', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com fratura', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com defeito', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com falha', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com problema', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com erro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vício', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material visível', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material claro', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material evidente', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material notório', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de eletrólito óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de óleo óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de fluido óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de líquido óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de substância óbvio', urgency: 'high', area: 'antenna' },
  { text: 'antena com capacitor com vazamento de material óbvio', urgency: 'high', area: 'antenna' },
  { text: 'internet com antena de internet desalinhada', urgency: 'medium', area: 'internet' },
  { text: 'internet com provedor fora do ar', urgency: 'high', area: 'internet' },
  { text: 'internet com IP bloqueado', urgency: 'medium', area: 'internet' },
  { text: 'internet com NAT duplicado', urgency: 'medium', area: 'internet' },
  { text: 'internet com porta bloqueada', urgency: 'medium', area: 'internet' },
  { text: 'internet com firewall bloqueando', urgency: 'medium', area: 'internet' },
  { text: 'internet com proxy falhando', urgency: 'medium', area: 'internet' },
  { text: 'internet com DNS não respondendo', urgency: 'medium', area: 'internet' },
  { text: 'internet com cache vencido', urgency: 'low', area: 'internet' },
  { text: 'internet com configuração antiga', urgency: 'low', area: 'internet' },
  { text: 'internet com lentidão no carregamento de página', urgency: 'low', area: 'internet' },
  { text: 'internet com delay no streaming', urgency: 'low', area: 'internet' },
  { text: 'internet com buffer constante', urgency: 'low', area: 'internet' },
  { text: 'internet com queda de frame', urgency: 'low', area: 'internet' },
  { text: 'internet com latência para jogos', urgency: 'low', area: 'internet' },
  { text: 'internet com perda de pacote em jogos', urgency: 'low', area: 'internet' },
  { text: 'internet com instabilidade em chamadas', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em video chamada', urgency: 'low', area: 'internet' },
  { text: 'internet com eco na chamada', urgency: 'low', area: 'internet' },
  { text: 'internet com áudio cortado', urgency: 'low', area: 'internet' },
  { text: 'internet com vídeo travado', urgency: 'low', area: 'internet' },
  { text: 'internet com compartilhamento lento', urgency: 'low', area: 'internet' },
  { text: 'internet com upload baixo', urgency: 'low', area: 'internet' },
  { text: 'internet com download oscilando', urgency: 'low', area: 'internet' },
  { text: 'internet com perda de pacote no upload', urgency: 'low', area: 'internet' },
  { text: 'internet com perda de pacote no download', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em horário específico', urgency: 'low', area: 'internet' },
  { text: 'internet com instabilidade em dispositivo específico', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em smartphone', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em notebook', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em smart tv', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em tablet', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em desktop', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em impressora', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em camera', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em sensor', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em relógio', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em Alexa', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em Google Home', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em roteador mesh', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em repetidor', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em PLC', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em powerline', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em access point', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em switch', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em hub', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em modem', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em bridge', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em repetidor de sinal', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em extensor de alcance', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em booster', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em amplificador', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em antena', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em receptor', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em transmissor', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em cliente', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em servidor', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em proxy', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em firewall', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em VPN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em VLAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em LAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em MAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em PAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em SAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em CAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em DAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em ELAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WLAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WWAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WPAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WMAN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WSN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WBN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WLN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WPN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WTN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WUN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WVN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WWN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WXN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WYN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em WZN', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W1N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W2N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W3N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W4N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W5N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W6N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W7N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W8N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W9N', urgency: 'low', area: 'internet' },
  { text: 'internet com queda em W0N', urgency: 'low', area: 'internet' },
  { text: 'fonte com placa com umidade', urgency: 'high', area: 'power' },
  { text: 'fonte com componente oxidado', urgency: 'high', area: 'power' },
  { text: 'fonte com trilha de fumaça', urgency: 'high', area: 'power' },
  { text: 'fonte com cheiro de plástico queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com superaquecimento na bateria', urgency: 'high', area: 'power' },
  { text: 'fonte com vazamento de eletrólito', urgency: 'high', area: 'power' },
  { text: 'fonte com bulbo estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com solda derretida', urgency: 'high', area: 'power' },
  { text: 'fonte com componente estourado visível', urgency: 'high', area: 'power' },
  { text: 'fonte com trilha de fogo', urgency: 'high', area: 'power' },
  { text: 'fonte com cheiro de metal queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com superaquecimento no transformador', urgency: 'high', area: 'power' },
  { text: 'fonte com vazamento de óleo', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com resistor queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com indutor estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com diodo queimado', urgency: 'high', area: 'power' },
  { text: 'fonte com transistor estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com integrado estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com CI estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com chip estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com microcontrolador estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com microprocessador estourado', urgency: 'high', area: 'power' },
  { text: 'fonte com memória estourada', urgency: 'high', area: 'power' },
  { text: 'fonte com RAM estourada', urgency: 'high', area: 'power' },
  { text: 'fonte com ROM estourada', urgency: 'high', area: 'power' },
  { text: 'fonte com Flash estourada', urgency: 'high', area: 'power' },
  { text: 'fonte com EEPROM estourada', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor inflado', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor estourado visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com inchamento', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com fuga', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com trinca', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com rachadura', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com fissura', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com quebra', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com fratura', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com defeito', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com falha', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com problema', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com erro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vício', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material visível', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material claro', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material evidente', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material notório', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de eletrólito óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de óleo óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de fluido óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de líquido óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de substância óbvio', urgency: 'high', area: 'power' },
  { text: 'fonte com capacitor com vazamento de material óbvio', urgency: 'high', area: 'power' },
];
